### ISSUE TITLE
Carthage / Cocoapods support ?

### ISSUE THREAD

**Issue by TheAbstractDev** [tomkowz/fireworks#1]
Hi,
Do you plain to publish your framework to Carthage & Cocoapods ?

**Comment by tomkowz** [comment]
Hi,

Didn't think about it. It had to be a small thing and exercise. Making it Cocoapod will force me somehow to maintain it, and for now I am out of time basically.

**Comment by TheAbstractDev** [comment]
Okay
Nice work 😊
